### ISSUE TITLE
Is Cate still being worked on?

### ISSUE THREAD

**Issue by PreetomBoro** [TheMilkies/Cate#8]
Though I haven't used Cate yet, I really like the syntax in the example. Much better than some industry standard. So I was wondering if this project is alive.

also... windows when?

**Comment by TheMilkies** [comment]
We are still working on it but slowly since it's pretty much done in our opinion.
The Windows release will come with the 3.0 rewrite (soon!)

**Comment by PreetomBoro** [comment]
eagerly waiting
